name: Deploy

#on:
#    push:
#        branches:
#            - master

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: ${{ runner.os }}-node-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-node-

            -   name: Build and push Docker images
                uses: docker/build-push-action@v1
                with:
                    #username: ${{ secrets.DOCKER_USERNAME }}
                    #password: ${{ secrets.DOCKER_PASSWORD }}
                    repository: ghcr.io/pmsipilot/docker-compose-viz
                    tag_with_ref: true
